from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    target = Path(path)
    text = target.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"expected exactly one anchor in {path!r}, found {count}: {old[:100]!r}")
    target.write_text(text.replace(old, new, 1))


rest_path = "packages/rakit-web/src/rakit_web/generated_rest.py"
replace_once(
    rest_path,
    "from rakit_core.generated_query import GeneratedFilterValue, build_generated_resource_query\n"
    "from rakit_core.query import FilterOperator, ResourceQuery\n",
    "from rakit_core.generated_query import GeneratedFilterValue, build_generated_resource_query\n"
    "from rakit_core.pagination import (\n"
    "    CursorPagination,\n"
    "    LimitOffsetPagination,\n"
    "    PagePagination,\n"
    "    PaginationStrategy,\n"
    ")\n"
    "from rakit_core.query import FilterOperator, ResourceQuery\n",
)
replace_once(
    rest_path,
    '_SINGLETON_QUERY_PARAMS = frozenset({"page", "per_page", "sort", "search"})\n',
    '_COMMON_QUERY_PARAMS = frozenset({"sort", "search"})\n'
    '_PAGINATION_QUERY_PARAMS = frozenset({"page", "per_page", "offset", "limit", "cursor"})\n',
)
old_helpers = '''def _parse_positive_int(api: CompiledResourceApi, name: str, raw: str | None, default: int) -> int:\n    if raw is None:\n        return default\n    try:\n        return int(raw)\n    except ValueError as exc:\n        raise _transport_error(api, "generated_api_invalid_pagination") from exc\n\n\ndef _filter_value(\n    api: CompiledResourceApi,\n    operator: FilterOperator,\n    raw_value: str,\n) -> object:\n    if operator is FilterOperator.IN:\n        values = tuple(part.strip() for part in raw_value.split(",") if part.strip())\n        if not values:\n            raise _transport_error(api, "generated_api_filter_value_invalid")\n        return values\n    if operator is FilterOperator.IS_NULL:\n        normalized = raw_value.strip().lower()\n        if normalized == "true":\n            return True\n        if normalized == "false":\n            return False\n        raise _transport_error(api, "generated_api_filter_value_invalid")\n    return raw_value\n\n\n'''
new_helpers = '''def _parse_int(\n    api: CompiledResourceApi,\n    name: str,\n    raw: str | None,\n    default: int,\n    *,\n    minimum: int,\n) -> int:\n    if raw is None:\n        return default\n    try:\n        value = int(raw)\n    except ValueError as exc:\n        raise _transport_error(api, "generated_api_invalid_pagination") from exc\n    if value < minimum:\n        raise _transport_error(api, "generated_api_invalid_pagination")\n    return value\n\n\ndef _query_params_for_strategy(api: CompiledResourceApi) -> frozenset[str]:\n    strategy = api.pagination.strategy\n    if strategy is PaginationStrategy.PAGE:\n        return _COMMON_QUERY_PARAMS | {"page", "per_page"}\n    if strategy is PaginationStrategy.LIMIT_OFFSET:\n        return _COMMON_QUERY_PARAMS | {"offset", "limit"}\n    return _COMMON_QUERY_PARAMS | {"cursor", "limit"}\n\n\ndef _parse_pagination(api: CompiledResourceApi, params: QueryParams):\n    policy = api.pagination\n    if policy.strategy is PaginationStrategy.PAGE:\n        page = _parse_int(api, "page", params.get("page"), 1, minimum=1)\n        size = _parse_int(\n            api,\n            "per_page",\n            params.get("per_page"),\n            policy.size.default,\n            minimum=1,\n        )\n        if not policy.size.accepts(size):\n            raise _transport_error(api, "generated_api_invalid_pagination")\n        return PagePagination(page=page, per_page=size)\n    if policy.strategy is PaginationStrategy.LIMIT_OFFSET:\n        offset = _parse_int(api, "offset", params.get("offset"), 0, minimum=0)\n        size = _parse_int(\n            api,\n            "limit",\n            params.get("limit"),\n            policy.size.default,\n            minimum=1,\n        )\n        if not policy.size.accepts(size):\n            raise _transport_error(api, "generated_api_invalid_pagination")\n        return LimitOffsetPagination(offset=offset, limit=size)\n    size = _parse_int(\n        api,\n        "limit",\n        params.get("limit"),\n        policy.size.default,\n        minimum=1,\n    )\n    if not policy.size.accepts(size):\n        raise _transport_error(api, "generated_api_invalid_pagination")\n    cursor = params.get("cursor")\n    if cursor == "":\n        raise _transport_error(api, "generated_api_invalid_pagination")\n    return CursorPagination(cursor=cursor, limit=size)\n\n\n'''
replace_once(rest_path, old_helpers, new_helpers)

old_parser = '''    items = tuple(params.multi_items())\n    raw_names = [name for name, _ in items]\n\n    for name in _SINGLETON_QUERY_PARAMS:\n        if raw_names.count(name) > 1:\n            raise _transport_error(api, "generated_api_query_parameter_duplicated")\n\n    filters: list[GeneratedFilterValue] = []\n    seen_filter_keys: set[str] = set()\n    for name, raw_value in items:\n        if name in _SINGLETON_QUERY_PARAMS:\n            continue\n        match = _FILTER_PATTERN.fullmatch(name)\n        if match is None:\n            raise _transport_error(api, "generated_api_query_parameter_not_allowed")\n        if name in seen_filter_keys:\n            raise _transport_error(api, "generated_api_filter_duplicated")\n        seen_filter_keys.add(name)\n        filter_name, raw_operator = match.groups()\n        try:\n            operator = FilterOperator(raw_operator or FilterOperator.EQ.value)\n        except ValueError as exc:\n            raise _transport_error(api, "generated_api_filter_operator_not_allowed") from exc\n        filters.append(\n            GeneratedFilterValue(\n                name=filter_name,\n                operator=operator,\n                value=_filter_value(api, operator, raw_value),\n            )\n        )\n\n    search = params.get("search")\n    if search is not None and not field_policy.search_fields:\n        raise _transport_error(api, "generated_api_search_not_allowed")\n\n    page = _parse_positive_int(api, "page", params.get("page"), 1)\n    per_page = _parse_positive_int(api, "per_page", params.get("per_page"), 25)\n    return build_generated_resource_query(\n        api,\n        field_policy,\n        sort=params.get("sort"),\n        page=page,\n        per_page=per_page,\n        filters=tuple(filters),\n        search=search,\n    )\n'''
new_parser = '''    items = tuple(params.multi_items())\n    raw_names = [name for name, _ in items]\n    allowed_query_params = _query_params_for_strategy(api)\n\n    for name in raw_names:\n        if name in _PAGINATION_QUERY_PARAMS and name not in allowed_query_params:\n            raise _transport_error(api, "generated_api_query_parameter_not_allowed")\n    for name in allowed_query_params:\n        if raw_names.count(name) > 1:\n            raise _transport_error(api, "generated_api_query_parameter_duplicated")\n\n    filters: list[GeneratedFilterValue] = []\n    seen_filter_keys: set[str] = set()\n    for name, raw_value in items:\n        if name in allowed_query_params:\n            continue\n        match = _FILTER_PATTERN.fullmatch(name)\n        if match is None:\n            raise _transport_error(api, "generated_api_query_parameter_not_allowed")\n        if name in seen_filter_keys:\n            raise _transport_error(api, "generated_api_filter_duplicated")\n        seen_filter_keys.add(name)\n        filter_name, raw_operator = match.groups()\n        try:\n            operator = FilterOperator(raw_operator or FilterOperator.EQ.value)\n        except ValueError as exc:\n            raise _transport_error(api, "generated_api_filter_operator_not_allowed") from exc\n        filters.append(\n            GeneratedFilterValue(\n                name=filter_name,\n                operator=operator,\n                value=raw_value,\n            )\n        )\n\n    search = params.get("search")\n    if search is not None and not field_policy.search_fields:\n        raise _transport_error(api, "generated_api_search_not_allowed")\n\n    return build_generated_resource_query(\n        api,\n        field_policy,\n        sort=params.get("sort"),\n        pagination=_parse_pagination(api, params),\n        filters=tuple(filters),\n        search=search,\n    )\n'''
replace_once(rest_path, old_parser, new_parser)

runtime_path = "packages/rakit-web/src/rakit_web/generated_rest_runtime.py"
replace_once(
    runtime_path,
    "from rakit_core.permissions import PermissionRequirement\n"
    "from rakit_core.query import PageResult\n",
    "from rakit_core.pagination import CursorPageResult, LimitOffsetResult, PageResult\n"
    "from rakit_core.permissions import PermissionRequirement\n",
)
old_response = '''def _list_response(binding: GeneratedRestBinding, result: object) -> JSONResponse:\n    if not isinstance(result, PageResult):\n        raise RakitError(\n            code=ErrorCode.INTERNAL_ERROR,\n            message="Generated list executor returned an invalid result.",\n            status_code=500,\n        )\n    return JSONResponse(\n        {\n            "data": [\n                serialize_generated_record(\n                    binding.api,\n                    item,\n                    schema_adapter=binding.schema_adapter,\n                )\n                for item in result.items\n            ],\n            "meta": {\n                "page": result.page,\n                "per_page": result.per_page,\n                "has_previous": result.has_previous,\n                "has_next": result.has_next,\n                "total": result.total_count,\n            },\n        },\n        headers={"Cache-Control": "no-store"},\n    )\n'''
new_response = '''def _list_response(binding: GeneratedRestBinding, result: object) -> JSONResponse:\n    if isinstance(result, PageResult):\n        meta: dict[str, object] = {\n            "page": result.page,\n            "per_page": result.per_page,\n            "has_previous": result.has_previous,\n            "has_next": result.has_next,\n            "total": result.total_count,\n        }\n    elif isinstance(result, LimitOffsetResult):\n        meta = {\n            "offset": result.offset,\n            "limit": result.limit,\n            "has_previous": result.has_previous,\n            "has_next": result.has_next,\n            "total": result.total_count,\n        }\n    elif isinstance(result, CursorPageResult):\n        meta = {\n            "limit": result.limit,\n            "previous_cursor": result.previous_cursor,\n            "next_cursor": result.next_cursor,\n        }\n    else:\n        raise RakitError(\n            code=ErrorCode.INTERNAL_ERROR,\n            message="Generated list executor returned an invalid result.",\n            status_code=500,\n        )\n    return JSONResponse(\n        {\n            "data": [\n                serialize_generated_record(\n                    binding.api,\n                    item,\n                    schema_adapter=binding.schema_adapter,\n                )\n                for item in result.items\n            ],\n            "meta": meta,\n        },\n        headers={"Cache-Control": "no-store"},\n    )\n'''
replace_once(runtime_path, old_response, new_response)
