from pathlib import Path

path = Path("packages/rakit-web/src/rakit_web/templates/relationships/inline_rows.html")
text = path.read_text()

if text.count("text-rakit-danger-text") != 2:
    raise RuntimeError("expected two invalid danger text tokens")
text = text.replace("text-rakit-danger-text", "text-rakit-danger")

old = '''<input class="sr-only" data-rakit-unlink-input type="checkbox" name="{{ panel.prefix }}unlink__{{ encoded }}" value="{{ encoded }}"{% if encoded in panel.pending_unlinks %} checked{% endif %} />{% if panel.unlink_destructive and encoded not in panel.pending_unlinks %}<button data-rakit-unlink-action data-rakit-unlink-prefix="{{ panel.prefix }}" data-rakit-unlink-identity="{{ encoded }}" data-rakit-unlink-destructive data-rakit-preview-unlink class="block w-full rounded px-3 py-2 text-left text-sm text-rakit-text-muted hover:bg-rakit-surface-subtle{% if row.delete_intent %} hidden{% endif %}" type="submit" name="{{ panel.prefix }}unlink_preview" value="{{ encoded }}" formaction="{{ panel.preview_path }}" formmethod="post" hx-post="{{ panel.preview_path }}" hx-include="closest form" hx-vals='{"{{ panel.prefix }}unlink_preview":"{{ encoded }}","{{ panel.prefix }}unlink__{{ encoded }}":"{{ encoded }}"}' hx-target="#rakit-dialog-root" hx-swap="innerHTML">Remove from relationship</button>{% else %}<button data-rakit-unlink-action data-rakit-unlink-prefix="{{ panel.prefix }}" data-rakit-unlink-identity="{{ encoded }}"{% if panel.unlink_destructive %} data-rakit-unlink-destructive{% endif %} class="block w-full rounded px-3 py-2 text-left text-sm text-rakit-text-muted hover:bg-rakit-surface-subtle{% if row.delete_intent %} hidden{% endif %}" type="button" aria-pressed="{{ 'true' if encoded in panel.pending_unlinks else 'false' }}"><span data-rakit-unlink-label>{{ 'Undo removal' if encoded in panel.pending_unlinks else 'Remove from relationship' }}</span></button>{% endif %}'''
new = '''{% if panel.unlink_destructive %}<input class="sr-only" data-rakit-unlink-input type="checkbox" name="{{ panel.prefix }}unlink__{{ encoded }}" value="{{ encoded }}"{% if encoded in panel.pending_unlinks %} checked{% endif %} />{% if encoded not in panel.pending_unlinks %}<button data-rakit-unlink-action data-rakit-unlink-prefix="{{ panel.prefix }}" data-rakit-unlink-identity="{{ encoded }}" data-rakit-unlink-destructive data-rakit-preview-unlink class="block w-full rounded px-3 py-2 text-left text-sm text-rakit-text-muted hover:bg-rakit-surface-subtle{% if row.delete_intent %} hidden{% endif %}" type="submit" name="{{ panel.prefix }}unlink_preview" value="{{ encoded }}" formaction="{{ panel.preview_path }}" formmethod="post" hx-post="{{ panel.preview_path }}" hx-include="closest form" hx-vals='{"{{ panel.prefix }}unlink_preview":"{{ encoded }}","{{ panel.prefix }}unlink__{{ encoded }}":"{{ encoded }}"}' hx-target="#rakit-dialog-root" hx-swap="innerHTML">Remove from relationship</button>{% endif %}{% else %}<label class="flex items-center gap-2 rounded px-3 py-2 text-left text-sm text-rakit-text-muted hover:bg-rakit-surface-subtle{% if row.delete_intent %} hidden{% endif %}"><input data-rakit-unlink-input type="checkbox" name="{{ panel.prefix }}unlink__{{ encoded }}" value="{{ encoded }}"{% if encoded in panel.pending_unlinks %} checked{% endif %} /><span>{{ 'Undo removal' if encoded in panel.pending_unlinks else 'Remove from relationship' }}</span></label>{% endif %}'''
if text.count(old) != 1:
    raise RuntimeError(f"expected one inline unlink control block, got {text.count(old)}")
text = text.replace(old, new)
path.write_text(text)
print("UI-06B source review fixes applied")
