from datetime import UTC, datetime

from sqlalchemy import JSON, Boolean, Column, DateTime, ForeignKey, String, Table, UniqueConstraint
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _now() -> datetime:
    return datetime.now(UTC)


class Base(DeclarativeBase):
    """Dedicated metadata for the built-in auth schema. Kept separate from
    any application-owned `DeclarativeBase` so this package's Alembic
    migrations only ever touch its own tables."""


user_roles = Table(
    "rakit_auth_user_roles",
    Base.metadata,
    Column("user_id", ForeignKey("rakit_auth_users.id"), primary_key=True),
    Column("role_id", ForeignKey("rakit_auth_roles.id"), primary_key=True),
)

role_permissions = Table(
    "rakit_auth_role_permissions",
    Base.metadata,
    Column("role_id", ForeignKey("rakit_auth_roles.id"), primary_key=True),
    Column("permission_id", ForeignKey("rakit_auth_permissions.id"), primary_key=True),
)


class User(Base):
    """The built-in user model. May serve as the application's main user
    model. Never stores a plaintext password -- only `password_hash`."""

    __tablename__ = "rakit_auth_users"

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String(320), unique=True, index=True)
    username: Mapped[str | None] = mapped_column(String(150), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    display_name: Mapped[str | None] = mapped_column(String(255))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_superuser: Mapped[bool] = mapped_column(Boolean, default=False)
    email_verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_now, onupdate=_now
    )

    roles: Mapped[list["Role"]] = relationship(secondary=user_roles, back_populates="users")

    def __init__(self, *, email: str, password_hash: str, **kwargs: object) -> None:
        # `mapped_column(default=...)` only applies at INSERT time, not at
        # object construction -- but callers (and CLI commands) must be able
        # to read secure defaults immediately, before any flush/commit.
        kwargs.setdefault("is_active", True)
        kwargs.setdefault("is_superuser", False)
        # Normalized the same way login-time identifiers are normalized
        # (see SQLAlchemyAuthBackend) -- stored normalized so the unique
        # constraint on `email` actually prevents case-variant duplicates
        # ("Ada@x" and "ada@x") and lookup at login always matches.
        super().__init__(email=email.strip().lower(), password_hash=password_hash, **kwargs)


class Role(Base):
    """An allow-only, non-hierarchical grouping of permissions. Role
    inheritance and hierarchical roles are roadmap items, not part of
    Plan 03."""

    __tablename__ = "rakit_auth_roles"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(150), unique=True)

    permissions: Mapped[list["Permission"]] = relationship(
        secondary=role_permissions, back_populates="roles"
    )
    users: Mapped[list[User]] = relationship(secondary=user_roles, back_populates="roles")


class Permission(Base):
    """A single stable permission key, generated by the permission catalogue
    (Task 5) from compiled resources/pages/actions/endpoints. `orphaned`
    marks a permission whose generating declaration no longer exists --
    synchronization never silently deletes a permission row, since a role
    may still reference it and deleting would silently revoke without
    record."""

    __tablename__ = "rakit_auth_permissions"

    id: Mapped[int] = mapped_column(primary_key=True)
    key: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    label: Mapped[str] = mapped_column(String(255), default="")
    group: Mapped[str] = mapped_column(String(255), default="")
    orphaned: Mapped[bool] = mapped_column(Boolean, default=False)

    roles: Mapped[list[Role]] = relationship(
        secondary=role_permissions, back_populates="permissions"
    )

    def __init__(self, *, key: str, **kwargs: object) -> None:
        kwargs.setdefault("label", "")
        kwargs.setdefault("group", "")
        kwargs.setdefault("orphaned", False)
        super().__init__(key=key, **kwargs)


class Session(Base):
    """An opaque server-side session. Stores only `token_hash` (SHA-256 hex
    digest of the raw browser token) -- the raw token itself is never
    persisted, matching the design's "opaque database sessions" guarantee.
    `user_agent`/`ip_address` are the only request metadata retained, kept
    deliberately minimal (no full request logging) since this table backs
    active authentication state, not an audit trail."""

    __tablename__ = "rakit_auth_sessions"
    __table_args__ = (UniqueConstraint("token_hash", name="uq_rakit_auth_sessions_token_hash"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    token_hash: Mapped[str] = mapped_column(String(64), index=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("rakit_auth_users.id"), index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    last_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    idle_expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    absolute_expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    user_agent: Mapped[str | None] = mapped_column(String(255))
    ip_address: Mapped[str | None] = mapped_column(String(64))


class IdempotencyRecord(Base):
    """A safe receipt only; never stores submitted form data or secrets."""

    __tablename__ = "rakit_auth_idempotency"
    __table_args__ = (UniqueConstraint("token_hash", name="uq_rakit_auth_idempotency_token_hash"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    token_hash: Mapped[str] = mapped_column(String(64), index=True)
    fingerprint: Mapped[str] = mapped_column(String(128))
    status: Mapped[str] = mapped_column(String(32))
    receipt: Mapped[dict[str, str | None] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
